### ISSUE TITLE
这篇代码的文章题目是？

### ISSUE THREAD

**Issue by qycools** [mint0126/Mult-scale-SAM#1]
作者你好，感谢你的贡献！

我遇到一些小麻烦不知道你是否能帮我解决一下，我最近在做遥感语义分割的相关研究，使用了UNetFormert网络在Potsdam数据集上做实验，使用了UNetFormert作者团队提供的源码，跑出来的miou精度和他们论文的miou精度相差甚远（他们的文章中Unetformer在Potsdam的miou精度为86.8），我跑出来的结果和你给出实验结果图片上关于Unetformer在Potsdam上的miou精度相近，但是你给出的两张potsdam实验结果图片的miou精度上在UnetFormer的精度不一致，一个是84.2一个是85.0，我不太清楚怎么回事，想读读你文章中具体的实验细节，并且不清楚你是否遇到UnetFormer无法复现精度的问题。

**Comment by ElodieDuboi** [comment]
Hey bro.! Have you solved the problem? I also encountered a similar problem when I tried to reproduce the unetformer. In fact, when I devided the Potsdam dataset according tothe author's suggestion, I only got about 80% of mIoU, which is far from the 86% reported by the authors and I have no idea how to address it.

**Comment by qycools** [comment]
> Hey bro.! Have you solved the problem? I also encountered a similar problem when I tried to reproduce the unetformer. In fact, when I devided the Potsdam dataset according tothe author's suggestion, I only got about 80% of mIoU, which is far from the 86% reported by the authors and I have no idea how to address it.

这个问题困扰了我是10天之久，在昨天早上我想我应该是找到问题所在了。精度差异过大我想不应该是网络模型以及训练过程中出问题，大概率是数据集预处理出问题了。有两种可能：
1、我找了相关引用过UNetFormer的文献，其中一篇[AerialFormer](https://github.com/UARK-AICV/AerialFormer)的源码，在https://github.com/UARK-AICV/AerialFormer/blob/e09134d685e17f30deba7b13b2b416e81f6f1375/aerialseg/datasets/potsdam_no_clutter.py#L13
该行中直接将训练的类别从6类删减掉‘clutter'变成5类，我尝试着利用相似想法在UNetFormer源码中进行改进后，最终Miou在85.5左右，很接近原论文的精度。
原论文中评价5类的做法是先用6类训练，然后在测试过程中只评价5类，我觉得上述做法和这个差异很大，原论文作者不可能在文章中以及源码不提到这一点。

2、我在中国的知乎网站上某个帖子的评论区（https://zhuanlan.zhihu.com/p/551978086）有人说可以复现有人说不可以复现，我觉得很纳闷，但是有位网友提到“看看是不是验证用的数据集错了，要用无边界的好像”，我突然想到Potsdam的标签集两个分别是5_Labels_all和5_Labels_all_noBoundary，于是我用5_Labels_all用于训练，用5_Labels_all_noBoundary用于测试，结果直接直逼论文精度，以下是我昨天跑的结果：
FtUNetFormer:
F1_ImSurf:0.9377196248648382, IOU_ImSurf:0.8827421148070491
F1_Building:0.9697556939230179, IOU_Building:0.9412871182134499
F1_LowVeg:0.8834567741829638, IOU_LowVeg:0.791242787341699
F1_Tree:0.8934037572030973, IOU_Tree:0.8073439278494519
F1_Car:0.9670341850292385, IOU_Car:0.9361724957535122
F1_Clutter:0.6282923563383918, IOU_Clutter:0.458036637210274
F1:0.9302740070406312, mIOU:0.8717576887930324, OA:0.9158798771046537

UNetFormer:
F1_ImSurf:0.9346088982734932, IOU_ImSurf:0.8772448885286576
F1_Building:0.9659575097795846, IOU_Building:0.9341564963869929
F1_LowVeg:0.8781388286924798, IOU_LowVeg:0.7827517799452993
F1_Tree:0.8904087264276627, IOU_Tree:0.802465509268999
F1_Car:0.9660343324693442, IOU_Car:0.9343002024201181
F1_Clutter:0.6083000190819707, IOU_Clutter:0.43709134685818424
F1:0.927029659128513, mIOU:0.8661837753100133, OA:0.911339621921142

ShelfNet:
F1_ImSurf:0.932303922968524, IOU_ImSurf:0.87319223421764
F1_Building:0.9661918656272078, IOU_Building:0.9345949538435324
F1_LowVeg:0.8761296926744532, IOU_LowVeg:0.7795647655816823
F1_Tree:0.8837091237221318, IOU_Tree:0.7916477170079085
F1_Car:0.9638580000218631, IOU_Car:0.9302373613290467
F1_Clutter:0.5949973001895124, IOU_Clutter:0.42348480915358244

FANet:
F1_ImSurf:0.9142719218720532, IOU_ImSurf:0.8420818621993041
F1_Building:0.9481893986575636, IOU_Building:0.901483021227757
F1_LowVeg:0.8513700973158828, IOU_LowVeg:0.7412048870801656
F1_Tree:0.8509717998131768, IOU_Tree:0.7406013182921146
F1_Car:0.9367939717174029, IOU_Car:0.881102953517496
F1_Clutter:0.51571348042003, IOU_Clutter:0.3474487395910385
F1:0.900319437875216, mIOU:0.8212948084633676, OA:0.8856339218888415

ABCNet结果我正在跑，还没出结果。但是我觉得很奇怪因为无论是UNetFormer还是ABCNet的作者在数据集处理时都没有提到这一点，因为Labels_all_noBoundary有黑边，相当于缓冲区，在缓冲区内不计算错误值，精度肯定会比在Labels_all中的要高。我又查了AerialFormer文章中数据集处理，他们提到“The dataset offers two types of annotations with non-eroded (NE) and eroded (E) options, which respectively with and without the boundary. To avoid ambiguity in labeling boundaries, all experimental results are performed and benchmarked on the eroded boundary dataset.”所以他们这些高精度的结果应该确定就是利用Labels_all_noBoundary来测试的。

你可以尝试一下我说的，我觉得第二点应该就是精度跑不上去的原因所在。祝你科研顺利！

**Comment by mint0126** [comment]
不好意思我才看见，我这篇论文还在投稿阶段。关于potsdam和Vaihingen数据集，测试阶段的标签集使用的是Labels_all_noBoundary处理的，在训练时没有考虑clutter类，训练测试均只考虑了5类的结果，而且我和原UNetFormer方法框架不同，所以结果也不是完全一样。

**Comment by ElodieDuboi** [comment]
Thanks a lot, I'll give a try.

**Comment by qycools** [comment]
> 不好意思我才看见，我这篇论文还在投稿阶段。关于potsdam和Vaihingen数据集，测试阶段的标签集使用的是Labels_all_noBoundary处理的，在训练时没有考虑clutter类，训练测试均只考虑了5类的结果，而且我和原UNetFormer方法框架不同，所以结果也不是完全一样。

训练和测试用的都是5类且Labels_all_noBoundary标签集吗？也就是说完全不预测'clutter'地物类别吗？而不仅仅只是‘clutter'不参与精度计算吗？
还有一个问题请教你一下，我看很多论文，比如ABCNet和UNetFormer这两篇文章，ABCNet是在crop_size 512*512做的，而UNetFormer是在crop_size 1024*1024下完成的，并且文章中的数据增强方式也不同，在这种情况下比较是否公平？在crop_size不同的情况下两篇论文中其他网络的精度完全一致，很显然UNetFormer没有重新做实验，所以我想知道在对比别人的网络时就是直接摘抄现有的精度的吗？那这样的话我在训练过程中用一些小tricks涨点岂不是并不是因为模型优越性导致的。初出茅庐，有很多不太懂的地方，大佬有空可以给点意见吗

**Comment by mint0126** [comment]
测试用的Labels_all_noBoundary标签集，训练时‘clutter’不参与精度计算，预测结果依旧是6类。按照严格意义上的公平而言的话，很多论文可能都没有做到公平比较。如果原论文提供了代码，你可以在你的设置下跑一下实验结果，如果实验结果与原论文相差不打的话，可以用这个结果作为比较。当前有很多方法是直接使用其他论文结果的，大前提是训练测试数据划分相同，应该也是可以的。

**Comment by qycools** [comment]
> 测试用的Labels_all_noBoundary标签集，训练时‘clutter’不参与精度计算，预测结果依旧是6类。按照严格意义上的公平而言的话，很多论文可能都没有做到公平比较。如果原论文提供了代码，你可以在你的设置下跑一下实验结果，如果实验结果与原论文相差不打的话，可以用这个结果作为比较。当前有很多方法是直接使用其他论文结果的，大前提是训练测试数据划分相同，应该也是可以的。

就是如果我跑出来的实验结果与原论文给出的精度差异不大的话，使用原论文的精度或者自己实验得出的精度都是被允许，只要向审稿人说明清楚我的实验划细节，比如数据集的划分，裁剪大小，数据增强等等，另外说明清楚自己是在统一框架下比较的的，与原论文中的一些实验细节有些差异，这样即使在自己的论文中标注别人网络精度与原论文中的精度有差异也是被允许的。我是这么理解的，对吗？

**Comment by mint0126** [comment]
我是这样做的

**Comment by qycools** [comment]
好的，感谢

**Comment by ElodieDuboi** [comment]
> > Hey bro.! Have you solved the problem? I also encountered a similar problem when I tried to reproduce the unetformer. In fact, when I devided the Potsdam dataset according tothe author's suggestion, I only got about 80% of mIoU, which is far from the 86% reported by the authors and I have no idea how to address it.
> 
> 这个问题困扰了我是10天之久，在昨天早上我想我应该是找到问题所在了。精度差异过大我想不应该是网络模型以及训练过程中出问题，大概率是数据集预处理出问题了。有两种可能： 1、我找了相关引用过UNetFormer的文献，其中一篇[AerialFormer](https://github.com/UARK-AICV/AerialFormer)的源码，在https://github.com/UARK-AICV/AerialFormer/blob/e09134d685e17f30deba7b13b2b416e81f6f1375/aerialseg/datasets/potsdam_no_clutter.py#L13 该行中直接将训练的类别从6类删减掉‘clutter'变成5类，我尝试着利用相似想法在UNetFormer源码中进行改进后，最终Miou在85.5左右，很接近原论文的精度。 原论文中评价5类的做法是先用6类训练，然后在测试过程中只评价5类，我觉得上述做法和这个差异很大，原论文作者不可能在文章中以及源码不提到这一点。
> 
> 2、我在中国的知乎网站上某个帖子的评论区（[https://zhuanlan.zhihu.com/p/551978086）有人说可以复现有人说不可以复现，我觉得很纳闷，但是有位网友提到“看看是不是验证用的数据集错了，要用无边界的好像”，我突然想到Potsdam的标签集两个分别是5_Labels_all和5_Labels_all_noBoundary，于是我用5_Labels_all用于训练，用5_Labels_all_noBoundary用于测试，结果直接直逼论文精度，以下是我昨天跑的结果：](https://zhuanlan.zhihu.com/p/551978086%EF%BC%89%E6%9C%89%E4%BA%BA%E8%AF%B4%E5%8F%AF%E4%BB%A5%E5%A4%8D%E7%8E%B0%E6%9C%89%E4%BA%BA%E8%AF%B4%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A4%8D%E7%8E%B0%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E5%BE%88%E7%BA%B3%E9%97%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E6%9C%89%E4%BD%8D%E7%BD%91%E5%8F%8B%E6%8F%90%E5%88%B0%E2%80%9C%E7%9C%8B%E7%9C%8B%E6%98%AF%E4%B8%8D%E6%98%AF%E9%AA%8C%E8%AF%81%E7%94%A8%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E9%94%99%E4%BA%86%EF%BC%8C%E8%A6%81%E7%94%A8%E6%97%A0%E8%BE%B9%E7%95%8C%E7%9A%84%E5%A5%BD%E5%83%8F%E2%80%9D%EF%BC%8C%E6%88%91%E7%AA%81%E7%84%B6%E6%83%B3%E5%88%B0Potsdam%E7%9A%84%E6%A0%87%E7%AD%BE%E9%9B%86%E4%B8%A4%E4%B8%AA%E5%88%86%E5%88%AB%E6%98%AF5_Labels_all%E5%92%8C5_Labels_all_noBoundary%EF%BC%8C%E4%BA%8E%E6%98%AF%E6%88%91%E7%94%A85_Labels_all%E7%94%A8%E4%BA%8E%E8%AE%AD%E7%BB%83%EF%BC%8C%E7%94%A85_Labels_all_noBoundary%E7%94%A8%E4%BA%8E%E6%B5%8B%E8%AF%95%EF%BC%8C%E7%BB%93%E6%9E%9C%E7%9B%B4%E6%8E%A5%E7%9B%B4%E9%80%BC%E8%AE%BA%E6%96%87%E7%B2%BE%E5%BA%A6%EF%BC%8C%E4%BB%A5%E4%B8%8B%E6%98%AF%E6%88%91%E6%98%A8%E5%A4%A9%E8%B7%91%E7%9A%84%E7%BB%93%E6%9E%9C%EF%BC%9A) FtUNetFormer: F1_ImSurf:0.9377196248648382, IOU_ImSurf:0.8827421148070491 F1_Building:0.9697556939230179, IOU_Building:0.9412871182134499 F1_LowVeg:0.8834567741829638, IOU_LowVeg:0.791242787341699 F1_Tree:0.8934037572030973, IOU_Tree:0.8073439278494519 F1_Car:0.9670341850292385, IOU_Car:0.9361724957535122 F1_Clutter:0.6282923563383918, IOU_Clutter:0.458036637210274 F1:0.9302740070406312, mIOU:0.8717576887930324, OA:0.9158798771046537
> 
> UNetFormer: F1_ImSurf:0.9346088982734932, IOU_ImSurf:0.8772448885286576 F1_Building:0.9659575097795846, IOU_Building:0.9341564963869929 F1_LowVeg:0.8781388286924798, IOU_LowVeg:0.7827517799452993 F1_Tree:0.8904087264276627, IOU_Tree:0.802465509268999 F1_Car:0.9660343324693442, IOU_Car:0.9343002024201181 F1_Clutter:0.6083000190819707, IOU_Clutter:0.43709134685818424 F1:0.927029659128513, mIOU:0.8661837753100133, OA:0.911339621921142
> 
> ShelfNet: F1_ImSurf:0.932303922968524, IOU_ImSurf:0.87319223421764 F1_Building:0.9661918656272078, IOU_Building:0.9345949538435324 F1_LowVeg:0.8761296926744532, IOU_LowVeg:0.7795647655816823 F1_Tree:0.8837091237221318, IOU_Tree:0.7916477170079085 F1_Car:0.9638580000218631, IOU_Car:0.9302373613290467 F1_Clutter:0.5949973001895124, IOU_Clutter:0.42348480915358244
> 
> FANet: F1_ImSurf:0.9142719218720532, IOU_ImSurf:0.8420818621993041 F1_Building:0.9481893986575636, IOU_Building:0.901483021227757 F1_LowVeg:0.8513700973158828, IOU_LowVeg:0.7412048870801656 F1_Tree:0.8509717998131768, IOU_Tree:0.7406013182921146 F1_Car:0.9367939717174029, IOU_Car:0.881102953517496 F1_Clutter:0.51571348042003, IOU_Clutter:0.3474487395910385 F1:0.900319437875216, mIOU:0.8212948084633676, OA:0.8856339218888415
> 
> ABCNet结果我正在跑，还没出结果。但是我觉得很奇怪因为无论是UNetFormer还是ABCNet的作者在数据集处理时都没有提到这一点，因为Labels_all_noBoundary有黑边，相当于缓冲区，在缓冲区内不计算错误值，精度肯定会比在Labels_all中的要高。我又查了AerialFormer文章中数据集处理，他们提到“The dataset offers two types of annotations with non-eroded (NE) and eroded (E) options, which respectively with and without the boundary. To avoid ambiguity in labeling boundaries, all experimental results are performed and benchmarked on the eroded boundary dataset.”所以他们这些高精度的结果应该确定就是利用Labels_all_noBoundary来测试的。
> 
> 你可以尝试一下我说的，我觉得第二点应该就是精度跑不上去的原因所在。祝你科研顺利！

Excuse me.Thank you a lot for your exciting reply. However, I feela bit confused about the label types you mentioned. I don't known how to use labels with boundary for training. Specifically, I am unsure how to transfer them into grayscale images. What value should be used to replace the points that belong to the boundaries?
After trying my best based on noboundary labels, it's sad that my results are still not satisfactory. I divided the Potsdam dataset according to the UNetformer paper and cropped all imagesinto non-overlapping 512*512 patches. The batchsize is to 32, learning rate to 2e-4, and the epochs to 100. During the training process, I used random flip and scale data augmentation methods, and only the first 5 classes were considered. When calculating the mIoU value, I removedall clutter class points. The final mIoU is about 81, which is still a certain distance from your ~85. If possible, would you like to share your experimental setup with me or give me some suggestions? This would help me a lot

**Comment by qycools** [comment]
> > > Hey bro.! Have you solved the problem? I also encountered a similar problem when I tried to reproduce the unetformer. In fact, when I devided the Potsdam dataset according tothe author's suggestion, I only got about 80% of mIoU, which is far from the 86% reported by the authors and I have no idea how to address it.
> > 
> > 
> > 这个问题困扰了我是10天之久，在昨天早上我想我应该是找到问题所在了。精度差异过大我想不应该是网络模型以及训练过程中出问题，大概率是数据集预处理出问题了。有两种可能： 1、我找了相关引用过UNetFormer的文献，其中一篇[AerialFormer](https://github.com/UARK-AICV/AerialFormer)的源码，在https://github.com/UARK-AICV/AerialFormer/blob/e09134d685e17f30deba7b13b2b416e81f6f1375/aerialseg/datasets/potsdam_no_clutter.py#L13 该行中直接将训练的类别从6类删减掉‘clutter'变成5类，我尝试着利用相似想法在UNetFormer源码中进行改进后，最终Miou在85.5左右，很接近原论文的精度。 原论文中评价5类的做法是先用6类训练，然后在测试过程中只评价5类，我觉得上述做法和这个差异很大，原论文作者不可能在文章中以及源码不提到这一点。
> > 2、我在中国的知乎网站上某个帖子的评论区（[https://zhuanlan.zhihu.com/p/551978086）有人说可以复现有人说不可以复现，我觉得很纳闷，但是有位网友提到“看看是不是验证用的数据集错了，要用无边界的好像”，我突然想到Potsdam的标签集两个分别是5_Labels_all和5_Labels_all_noBoundary，于是我用5_Labels_all用于训练，用5_Labels_all_noBoundary用于测试，结果直接直逼论文精度，以下是我昨天跑的结果：](https://zhuanlan.zhihu.com/p/551978086%EF%BC%89%E6%9C%89%E4%BA%BA%E8%AF%B4%E5%8F%AF%E4%BB%A5%E5%A4%8D%E7%8E%B0%E6%9C%89%E4%BA%BA%E8%AF%B4%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A4%8D%E7%8E%B0%EF%BC%8C%E6%88%91%E8%A7%89%E5%BE%97%E5%BE%88%E7%BA%B3%E9%97%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E6%9C%89%E4%BD%8D%E7%BD%91%E5%8F%8B%E6%8F%90%E5%88%B0%E2%80%9C%E7%9C%8B%E7%9C%8B%E6%98%AF%E4%B8%8D%E6%98%AF%E9%AA%8C%E8%AF%81%E7%94%A8%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86%E9%94%99%E4%BA%86%EF%BC%8C%E8%A6%81%E7%94%A8%E6%97%A0%E8%BE%B9%E7%95%8C%E7%9A%84%E5%A5%BD%E5%83%8F%E2%80%9D%EF%BC%8C%E6%88%91%E7%AA%81%E7%84%B6%E6%83%B3%E5%88%B0Potsdam%E7%9A%84%E6%A0%87%E7%AD%BE%E9%9B%86%E4%B8%A4%E4%B8%AA%E5%88%86%E5%88%AB%E6%98%AF5_Labels_all%E5%92%8C5_Labels_all_noBoundary%EF%BC%8C%E4%BA%8E%E6%98%AF%E6%88%91%E7%94%A85_Labels_all%E7%94%A8%E4%BA%8E%E8%AE%AD%E7%BB%83%EF%BC%8C%E7%94%A85_Labels_all_noBoundary%E7%94%A8%E4%BA%8E%E6%B5%8B%E8%AF%95%EF%BC%8C%E7%BB%93%E6%9E%9C%E7%9B%B4%E6%8E%A5%E7%9B%B4%E9%80%BC%E8%AE%BA%E6%96%87%E7%B2%BE%E5%BA%A6%EF%BC%8C%E4%BB%A5%E4%B8%8B%E6%98%AF%E6%88%91%E6%98%A8%E5%A4%A9%E8%B7%91%E7%9A%84%E7%BB%93%E6%9E%9C%EF%BC%9A) FtUNetFormer: F1_ImSurf:0.9377196248648382, IOU_ImSurf:0.8827421148070491 F1_Building:0.9697556939230179, IOU_Building:0.9412871182134499 F1_LowVeg:0.8834567741829638, IOU_LowVeg:0.791242787341699 F1_Tree:0.8934037572030973, IOU_Tree:0.8073439278494519 F1_Car:0.9670341850292385, IOU_Car:0.9361724957535122 F1_Clutter:0.6282923563383918, IOU_Clutter:0.458036637210274 F1:0.9302740070406312, mIOU:0.8717576887930324, OA:0.9158798771046537
> > UNetFormer: F1_ImSurf:0.9346088982734932, IOU_ImSurf:0.8772448885286576 F1_Building:0.9659575097795846, IOU_Building:0.9341564963869929 F1_LowVeg:0.8781388286924798, IOU_LowVeg:0.7827517799452993 F1_Tree:0.8904087264276627, IOU_Tree:0.802465509268999 F1_Car:0.9660343324693442, IOU_Car:0.9343002024201181 F1_Clutter:0.6083000190819707, IOU_Clutter:0.43709134685818424 F1:0.927029659128513, mIOU:0.8661837753100133, OA:0.911339621921142
> > ShelfNet: F1_ImSurf:0.932303922968524, IOU_ImSurf:0.87319223421764 F1_Building:0.9661918656272078, IOU_Building:0.9345949538435324 F1_LowVeg:0.8761296926744532, IOU_LowVeg:0.7795647655816823 F1_Tree:0.8837091237221318, IOU_Tree:0.7916477170079085 F1_Car:0.9638580000218631, IOU_Car:0.9302373613290467 F1_Clutter:0.5949973001895124, IOU_Clutter:0.42348480915358244
> > FANet: F1_ImSurf:0.9142719218720532, IOU_ImSurf:0.8420818621993041 F1_Building:0.9481893986575636, IOU_Building:0.901483021227757 F1_LowVeg:0.8513700973158828, IOU_LowVeg:0.7412048870801656 F1_Tree:0.8509717998131768, IOU_Tree:0.7406013182921146 F1_Car:0.9367939717174029, IOU_Car:0.881102953517496 F1_Clutter:0.51571348042003, IOU_Clutter:0.3474487395910385 F1:0.900319437875216, mIOU:0.8212948084633676, OA:0.8856339218888415
> > ABCNet结果我正在跑，还没出结果。但是我觉得很奇怪因为无论是UNetFormer还是ABCNet的作者在数据集处理时都没有提到这一点，因为Labels_all_noBoundary有黑边，相当于缓冲区，在缓冲区内不计算错误值，精度肯定会比在Labels_all中的要高。我又查了AerialFormer文章中数据集处理，他们提到“The dataset offers two types of annotations with non-eroded (NE) and eroded (E) options, which respectively with and without the boundary. To avoid ambiguity in labeling boundaries, all experimental results are performed and benchmarked on the eroded boundary dataset.”所以他们这些高精度的结果应该确定就是利用Labels_all_noBoundary来测试的。
> > 你可以尝试一下我说的，我觉得第二点应该就是精度跑不上去的原因所在。祝你科研顺利！
> 
> Excuse me.Thank you a lot for your exciting reply. However, I feela bit confused about the label types you mentioned. I don't known how to use labels with boundary for training. Specifically, I am unsure how to transfer them into grayscale images. What value should be used to replace the points that belong to the boundaries? After trying my best based on noboundary labels, it's sad that my results are still not satisfactory. I divided the Potsdam dataset according to the UNetformer paper and cropped all imagesinto non-overlapping 512*512 patches. The batchsize is to 32, learning rate to 2e-4, and the epochs to 100. During the training process, I used random flip and scale data augmentation methods, and only the first 5 classes were considered. When calculating the mIoU value, I removedall clutter class points. The final mIoU is about 81, which is still a certain distance from your ~85. If possible, would you like to share your experimental setup with me or give me some suggestions? This would help me a lot

你有邮箱或者其他通讯软件吗？我发你

**Comment by ElodieDuboi** [comment]
Oh, thank you. If possible, please send me at ddubois9911@gmail.com. Best whishes.
